package go_hugipipes_musical_notes

import (
	tu "github.com/informaticon/lib.go.base.test-utils"
	"math"
	"testing"
)

const (
	scaleJust1  = 16.0 / 15.0
	scaleJust2  = 9.0 / 8.0
	scaleJust3  = 6.0 / 5.0
	scaleJust4  = 5.0 / 4.0
	scaleJust5  = 4.0 / 3.0
	scaleJust6  = 45.0 / 32.0
	scaleJust7  = 3.0 / 2.0
	scaleJust8  = 8.0 / 5.0
	scaleJust9  = 5.0 / 3.0
	scaleJust10 = 9.0 / 5.0
	scaleJust11 = 15.0 / 8.0
)

func TestFromBaseNote(t *testing.T) {
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, C, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, Cis, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, D, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, Dis, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, E, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, F, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, Fis, 10), 2), roundFloat(10*scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, G, 10), 2), roundFloat(10*scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, Gis, 10), 2), roundFloat(10*scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, A, 10), 2), roundFloat(10*scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, Ais, 10), 2), roundFloat(10*scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(C, B, 10), 2), roundFloat(10*scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, Cis, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, D, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, Dis, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, E, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, F, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, Fis, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, G, 10), 2), roundFloat(10*scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, Gis, 10), 2), roundFloat(10*scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, A, 10), 2), roundFloat(10*scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, Ais, 10), 2), roundFloat(10*scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, B, 10), 2), roundFloat(10*scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Cis, C, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(D, D, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, Dis, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, E, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, F, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, Fis, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, G, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, Gis, 10), 2), roundFloat(10*scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, A, 10), 2), roundFloat(10*scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, Ais, 10), 2), roundFloat(10*scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, B, 10), 2), roundFloat(10*scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, C, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(D, Cis, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, Dis, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, E, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, F, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, Fis, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, G, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, Gis, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, A, 10), 2), roundFloat(10*scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, Ais, 10), 2), roundFloat(10*scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, B, 10), 2), roundFloat(10*scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, C, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, Cis, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Dis, D, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(E, E, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, F, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, Fis, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, G, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, Gis, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, A, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, Ais, 10), 2), roundFloat(10*scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, B, 10), 2), roundFloat(10*scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, C, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, Cis, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, D, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(E, Dis, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(F, F, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, Fis, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, G, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, Gis, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, A, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, Ais, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, B, 10), 2), roundFloat(10*scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, C, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, Cis, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, D, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, Dis, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(F, E, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, Fis, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, G, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, Gis, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, A, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, Ais, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, B, 10), 2), roundFloat(10*scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, C, 10), 2), roundFloat(10*scaleJust6/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, Cis, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, D, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, Dis, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, E, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Fis, F, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(G, G, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, Gis, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, A, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, Ais, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, B, 10), 2), roundFloat(10*scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, C, 10), 2), roundFloat(10*scaleJust5/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, Cis, 10), 2), roundFloat(10*scaleJust6/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, D, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, Dis, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, E, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, F, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(G, Fis, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, Gis, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, A, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, Ais, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, B, 10), 2), roundFloat(10*scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, C, 10), 2), roundFloat(10*scaleJust4/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, Cis, 10), 2), roundFloat(10*scaleJust5/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, D, 10), 2), roundFloat(10*scaleJust6/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, Dis, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, E, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, F, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, Fis, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Gis, G, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(A, A, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, Ais, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, B, 10), 2), roundFloat(10*scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, C, 10), 2), roundFloat(10*scaleJust3/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, Cis, 10), 2), roundFloat(10*scaleJust4/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, D, 10), 2), roundFloat(10*scaleJust5/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, Dis, 10), 2), roundFloat(10*scaleJust6/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, E, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, F, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, Fis, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, G, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(A, Gis, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, Ais, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, B, 10), 2), roundFloat(10*scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, C, 10), 2), roundFloat(10*scaleJust2/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, Cis, 10), 2), roundFloat(10*scaleJust3/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, D, 10), 2), roundFloat(10*scaleJust4/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, Dis, 10), 2), roundFloat(10*scaleJust5/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, E, 10), 2), roundFloat(10*scaleJust6/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, F, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, Fis, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, G, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, Gis, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(Ais, A, 10), 2), roundFloat(10*scaleJust11/2, 2), t)

	tu.AssertEq(roundFloat(justTempFromBaseNote(B, B, 10), 2), roundFloat(10, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, C, 10), 2), roundFloat(10*scaleJust1/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, Cis, 10), 2), roundFloat(10*scaleJust2/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, D, 10), 2), roundFloat(10*scaleJust3/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, Dis, 10), 2), roundFloat(10*scaleJust4/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, E, 10), 2), roundFloat(10*scaleJust5/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, F, 10), 2), roundFloat(10*scaleJust6/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, Fis, 10), 2), roundFloat(10*scaleJust7/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, G, 10), 2), roundFloat(10*scaleJust8/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, Gis, 10), 2), roundFloat(10*scaleJust9/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, A, 10), 2), roundFloat(10*scaleJust10/2, 2), t)
	tu.AssertEq(roundFloat(justTempFromBaseNote(B, Ais, 10), 2), roundFloat(10*scaleJust11/2, 2), t)
}

func TestToBaseNote(t *testing.T) {
	tu.AssertEq(roundFloat(justTempToBaseNote(C, C, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, Cis, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, D, 10), 2), roundFloat(10/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, Dis, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, E, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, F, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, Fis, 10), 2), roundFloat(10.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, G, 10), 2), roundFloat(10.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, Gis, 10), 2), roundFloat(10.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, A, 440), 2), roundFloat(264, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, Ais, 10), 2), roundFloat(10.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(C, B, 10), 2), roundFloat(10.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, Cis, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, D, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, Dis, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, E, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, F, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, Fis, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, G, 10), 2), roundFloat(10.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, Gis, 10), 2), roundFloat(10.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, A, 10), 2), roundFloat(10.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, Ais, 10), 2), roundFloat(10.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, B, 10), 2), roundFloat(10.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Cis, C, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(D, D, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, Dis, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, E, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, F, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, Fis, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, G, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, Gis, 10), 2), roundFloat(10.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, A, 10), 2), roundFloat(10.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, Ais, 10), 2), roundFloat(10.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, B, 10), 2), roundFloat(10.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, C, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(D, Cis, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, Dis, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, E, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, F, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, Fis, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, G, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, Gis, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, A, 10), 2), roundFloat(10.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, Ais, 10), 2), roundFloat(10.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, B, 10), 2), roundFloat(10.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, C, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, Cis, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Dis, D, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(E, E, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, F, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, Fis, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, G, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, Gis, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, A, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, Ais, 10), 2), roundFloat(10.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, B, 10), 2), roundFloat(10.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, C, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, Cis, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, D, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(E, Dis, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(F, F, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, Fis, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, G, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, Gis, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, A, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, Ais, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, B, 10), 2), roundFloat(10.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, C, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, Cis, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, D, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, Dis, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(F, E, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, Fis, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, G, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, Gis, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, A, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, Ais, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, B, 10), 2), roundFloat(10.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, C, 10), 2), roundFloat(20.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, Cis, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, D, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, Dis, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, E, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Fis, F, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(G, G, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, Gis, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, A, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, Ais, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, B, 10), 2), roundFloat(10.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, C, 10), 2), roundFloat(20.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, Cis, 10), 2), roundFloat(20.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, D, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, Dis, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, E, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, F, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(G, Fis, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, Gis, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, A, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, Ais, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, B, 10), 2), roundFloat(10.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, C, 10), 2), roundFloat(20.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, Cis, 10), 2), roundFloat(20.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, D, 10), 2), roundFloat(20.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, Dis, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, E, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, F, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, Fis, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Gis, G, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(A, A, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, Ais, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, B, 10), 2), roundFloat(10.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, C, 10), 2), roundFloat(20.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, Cis, 10), 2), roundFloat(20.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, D, 10), 2), roundFloat(20.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, Dis, 10), 2), roundFloat(20.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, E, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, F, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, Fis, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, G, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(A, Gis, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, Ais, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, B, 10), 2), roundFloat(10.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, C, 10), 2), roundFloat(20/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, Cis, 10), 2), roundFloat(20.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, D, 10), 2), roundFloat(20.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, Dis, 10), 2), roundFloat(20.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, E, 10), 2), roundFloat(20.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, F, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, Fis, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, G, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, Gis, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(Ais, A, 10), 2), roundFloat(20.0/scaleJust11, 2), t)

	tu.AssertEq(roundFloat(justTempToBaseNote(B, B, 10), 2), roundFloat(10.0, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, C, 10), 2), roundFloat(20.0/scaleJust1, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, Cis, 10), 2), roundFloat(20.0/scaleJust2, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, D, 10), 2), roundFloat(20.0/scaleJust3, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, Dis, 10), 2), roundFloat(20.0/scaleJust4, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, E, 10), 2), roundFloat(20.0/scaleJust5, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, F, 10), 2), roundFloat(20.0/scaleJust6, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, Fis, 10), 2), roundFloat(20.0/scaleJust7, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, G, 10), 2), roundFloat(20.0/scaleJust8, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, Gis, 10), 2), roundFloat(20.0/scaleJust9, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, A, 10), 2), roundFloat(20.0/scaleJust10, 2), t)
	tu.AssertEq(roundFloat(justTempToBaseNote(B, Ais, 10), 2), roundFloat(20.0/scaleJust11, 2), t)
}

func TestIntervalToCents(t *testing.T) {
	tu.AssertEq(intervalToCents(1), 0.0, t)
	tu.AssertEq(intervalToCents(2), 1200.0, t)
	tu.AssertEq(intervalToCents(0.5), -1200.0, t)
	tu.AssertEq(roundFloat(intervalToCents(2.5), 2), 1586.31, t)
}

func intervalToCents(interval float64) float64 {
	return math.Log(interval) / log2 * 1200
}

func Test_JustScaleFromBaseNote(t *testing.T) {
	n := JustScaleFromBaseNote(264)
	tu.AssertEq(n[0], 264, t)
	tu.AssertEq(n[1], 281.6, t)
	tu.AssertEq(n[2], 297, t)
	tu.AssertEq(n[3], 316.8, t)
	tu.AssertEq(n[4], 330, t)
	tu.AssertEq(n[5], 352, t)
	tu.AssertEq(n[6], 371.25, t)
	tu.AssertEq(n[7], 396, t)
	tu.AssertEq(n[8], 422.4, t)
	tu.AssertEq(n[9], 440, t)
	tu.AssertEq(n[10], 475.2, t)
	tu.AssertEq(n[11], 495, t)
}

func Test_JustScaleFromBaseNoteWithinOctave(t *testing.T) {
	nC := JustScaleFromBaseNoteWithinOctave(NewSimpleNote(264, C))
	tu.AssertEq(len(nC), 12, t)
	tu.AssertEq(nC[0], NewSimpleNote(264, C), t)
	tu.AssertEq(nC[1], NewSimpleNote(281.6, Cis), t)
	tu.AssertEq(nC[2], NewSimpleNote(297, D), t)
	tu.AssertEq(nC[3], NewSimpleNote(316.8, Dis), t)
	tu.AssertEq(nC[4], NewSimpleNote(330, E), t)
	tu.AssertEq(nC[5], NewSimpleNote(352, F), t)
	tu.AssertEq(nC[6], NewSimpleNote(371.25, Fis), t)
	tu.AssertEq(nC[7], NewSimpleNote(396, G), t)
	tu.AssertEq(nC[8], NewSimpleNote(422.4, Gis), t)
	tu.AssertEq(nC[9], NewSimpleNote(440, A), t)
	tu.AssertEq(nC[10], NewSimpleNote(475.2, Ais), t)
	tu.AssertEq(nC[11], NewSimpleNote(495, B), t)

	nCis := JustScaleFromBaseNoteWithinOctave(NewSimpleNote(264, Cis))
	tu.AssertEq(len(nCis), 12, t)
	tu.AssertEq(nCis[0], NewSimpleNote(264, Cis), t)
	tu.AssertEq(nCis[1], NewSimpleNote(281.6, D), t)
	tu.AssertEq(nCis[2], NewSimpleNote(297, Dis), t)
	tu.AssertEq(nCis[3], NewSimpleNote(316.8, E), t)
	tu.AssertEq(nCis[4], NewSimpleNote(330, F), t)
	tu.AssertEq(nCis[5], NewSimpleNote(352, Fis), t)
	tu.AssertEq(nCis[6], NewSimpleNote(371.25, G), t)
	tu.AssertEq(nCis[7], NewSimpleNote(396, Gis), t)
	tu.AssertEq(nCis[8], NewSimpleNote(422.4, A), t)
	tu.AssertEq(nCis[9], NewSimpleNote(440, Ais), t)
	tu.AssertEq(nCis[10], NewSimpleNote(475.2, B), t)
	tu.AssertEq(nCis[11], NewSimpleNote(495.0/2, C), t)

	nE := JustScaleFromBaseNoteWithinOctave(NewSimpleNote(264, E))
	tu.AssertEq(len(nC), 12, t)
	tu.AssertEq(nE[0], NewSimpleNote(264, E), t)
	tu.AssertEq(nE[1], NewSimpleNote(281.6, F), t)
	tu.AssertEq(nE[2], NewSimpleNote(297, Fis), t)
	tu.AssertEq(nE[3], NewSimpleNote(316.8, G), t)
	tu.AssertEq(nE[4], NewSimpleNote(330, Gis), t)
	tu.AssertEq(nE[5], NewSimpleNote(352, A), t)
	tu.AssertEq(nE[6], NewSimpleNote(371.25, Ais), t)
	tu.AssertEq(nE[7], NewSimpleNote(396, B), t)
	tu.AssertEq(nE[8], NewSimpleNote(422.4/2, C), t)
	tu.AssertEq(nE[9], NewSimpleNote(440/2, Cis), t)
	tu.AssertEq(nE[10], NewSimpleNote(475.2/2, D), t)
	tu.AssertEq(nE[11], NewSimpleNote(495.0/2, Dis), t)

	nGis := JustScaleFromBaseNoteWithinOctave(NewSimpleNote(264, Gis))
	tu.AssertEq(len(nC), 12, t)
	tu.AssertEq(nGis[0], NewSimpleNote(264, Gis), t)
	tu.AssertEq(nGis[1], NewSimpleNote(281.6, A), t)
	tu.AssertEq(nGis[2], NewSimpleNote(297, Ais), t)
	tu.AssertEq(nGis[3], NewSimpleNote(316.8, B), t)
	tu.AssertEq(nGis[4], NewSimpleNote(330.0/2, C), t)
	tu.AssertEq(nGis[5], NewSimpleNote(352.0/2, Cis), t)
	tu.AssertEq(nGis[6], NewSimpleNote(371.25/2, D), t)
	tu.AssertEq(nGis[7], NewSimpleNote(396.0/2, Dis), t)
	tu.AssertEq(nGis[8], NewSimpleNote(422.4/2, E), t)
	tu.AssertEq(nGis[9], NewSimpleNote(440/2, F), t)
	tu.AssertEq(nGis[10], NewSimpleNote(475.2/2, Fis), t)
	tu.AssertEq(nGis[11], NewSimpleNote(495.0/2, G), t)

	nB := JustScaleFromBaseNoteWithinOctave(NewSimpleNote(264, B))
	tu.AssertEq(len(nB), 12, t)
	tu.AssertEq(nB[0], NewSimpleNote(264, B), t)
	tu.AssertEq(nB[1], NewSimpleNote(281.6/2, C), t)
	tu.AssertEq(nB[2], NewSimpleNote(297.0/2, Cis), t)
	tu.AssertEq(nB[3], NewSimpleNote(316.8/2, D), t)
	tu.AssertEq(nB[4], NewSimpleNote(330.0/2, Dis), t)
	tu.AssertEq(nB[5], NewSimpleNote(352.0/2, E), t)
	tu.AssertEq(nB[6], NewSimpleNote(371.25/2, F), t)
	tu.AssertEq(nB[7], NewSimpleNote(396.0/2, Fis), t)
	tu.AssertEq(nB[8], NewSimpleNote(422.4/2, G), t)
	tu.AssertEq(nB[9], NewSimpleNote(440.0/2, Gis), t)
	tu.AssertEq(nB[10], NewSimpleNote(475.2/2, A), t)
	tu.AssertEq(nB[11], NewSimpleNote(495.0/2, Ais), t)
}
